/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sunrisedental.ui;
import com.sunrisedental.client.ServiceClient;
import com.sunrisedental.web.dto.BillDTO;

import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;

import javax.swing.JOptionPane;
/**
 *
 * @author my pc
 */
public class BillingFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BillingFrame.class.getName());

    /**
     * Creates new form BillingFrame
     */
    public BillingFrame() {
       initComponents();
        
          setLocationRelativeTo(null);

    txtPatientName.setEditable(false);
    txtDentistName.setEditable(false);
    txtTreatment.setEditable(false);
    txtTreatmentCost.setEditable(false);
    txtTotal.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn1Bill = new javax.swing.JPanel();
        pn1Bill1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblAppointmentId = new javax.swing.JLabel();
        txtAppointmentId = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblTreatment = new javax.swing.JLabel();
        txtTreatment = new javax.swing.JTextField();
        lblTreatmentCost = new javax.swing.JLabel();
        txtTreatmentCost = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        lblPatientName = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        lblPDentistName = new javax.swing.JLabel();
        txtDentistName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn1Bill1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("PATIENT BILLING");

        lblAppointmentId.setText("Appointment ID");

        btnSearch.setBackground(new java.awt.Color(0, 153, 204));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("SEARCH");
        btnSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        lblTreatment.setText("Treatment");

        lblTreatmentCost.setText("Treatment Cost");

        txtTreatmentCost.addActionListener(this::txtTreatmentCostActionPerformed);

        lblTotal.setText("Total Amount");

        btnClear.setBackground(new java.awt.Color(0, 153, 255));
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("CLEAR");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnBack.setBackground(new java.awt.Color(0, 153, 255));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(this::btnBackActionPerformed);

        btnPrint.setBackground(new java.awt.Color(0, 153, 255));
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setText("PRINT BILL");
        btnPrint.addActionListener(this::btnPrintActionPerformed);

        lblPatientName.setText("Patient Name");

        lblPDentistName.setText("Dentist Name");

        javax.swing.GroupLayout pn1Bill1Layout = new javax.swing.GroupLayout(pn1Bill1);
        pn1Bill1.setLayout(pn1Bill1Layout);
        pn1Bill1Layout.setHorizontalGroup(
            pn1Bill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn1Bill1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(pn1Bill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn1Bill1Layout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn1Bill1Layout.createSequentialGroup()
                        .addGroup(pn1Bill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAppointmentId, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pn1Bill1Layout.createSequentialGroup()
                                .addGroup(pn1Bill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblPatientName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPDentistName, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                                .addGap(16, 16, 16))
                            .addComponent(lblTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pn1Bill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn1Bill1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pn1Bill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pn1Bill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtDentistName, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAppointmentId, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pn1Bill1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(txtTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn1Bill1Layout.createSequentialGroup()
                        .addGroup(pn1Bill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTreatmentCost, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(pn1Bill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTreatmentCost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn1Bill1Layout.createSequentialGroup()
                        .addComponent(btnClear)
                        .addGap(31, 31, 31)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnPrint)
                        .addGap(46, 46, 46))))
        );
        pn1Bill1Layout.setVerticalGroup(
            pn1Bill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn1Bill1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(pn1Bill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAppointmentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAppointmentId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(pn1Bill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pn1Bill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPDentistName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDentistName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pn1Bill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pn1Bill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTreatmentCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTreatmentCost, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pn1Bill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(pn1Bill1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn1BillLayout = new javax.swing.GroupLayout(pn1Bill);
        pn1Bill.setLayout(pn1BillLayout);
        pn1BillLayout.setHorizontalGroup(
            pn1BillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn1BillLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn1Bill1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn1BillLayout.setVerticalGroup(
            pn1BillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn1BillLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pn1Bill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn1Bill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn1Bill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String appointmentText = txtAppointmentId.getText().trim();

        if (appointmentText.isEmpty()) {

            JOptionPane.showMessageDialog(
                this,
                "Please enter Appointment ID.",
                "Missing Appointment ID",
                JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        int appointmentId;

        try {

            appointmentId = Integer.parseInt(appointmentText);

            if (appointmentId <= 0) {
                throw new NumberFormatException();
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                this,
                "Please enter a valid numeric Appointment ID.",
                "Invalid Appointment ID",
                JOptionPane.ERROR_MESSAGE
            );

            return;
        }

        try {

            BillDTO bill =
            ServiceClient.billing()
            .calculateBill(appointmentId);

            if (bill == null) {

                JOptionPane.showMessageDialog(
                    this,
                    "Appointment not found or treatment price is unavailable.",
                    "Bill Not Found",
                    JOptionPane.WARNING_MESSAGE
                );

                clearBill();

                return;
            }

            txtPatientName.setText(
                bill.patientName
            );

            txtDentistName.setText(
                bill.dentistName
            );

            txtTreatment.setText(
                bill.treatmentType
            );

            // Treatment Cost
            txtTreatmentCost.setText(
                String.format(
                    "Rs. %.2f",
                    bill.treatmentCost
                )
            );

            // Total
            txtTotal.setText(
                String.format(
                    "Rs. %.2f",
                    bill.total
                )
            );

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                this,
                "Unable to retrieve bill.\n\n"
                + e.getMessage(),
                "Billing Error",
                JOptionPane.ERROR_MESSAGE
            );

            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtTreatmentCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTreatmentCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTreatmentCostActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtPatientName.setText("");
        txtDentistName.setText("");
        txtAppointmentId.setText("");
        txtTreatment.setText("");
        txtTreatmentCost.setText("");
        txtTotal.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        DashboardFrame dashboard = new DashboardFrame();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        if (txtPatientName.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(
                this,
                "Please search an appointment first.",
                "No Bill",
                JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        PrinterJob printerJob = PrinterJob.getPrinterJob();

        printerJob.setPrintable(new Printable() {

            @Override
            public int print(
                java.awt.Graphics graphics,
                PageFormat pageFormat,
                int pageIndex) throws PrinterException {

                if (pageIndex > 0) {

                    return NO_SUCH_PAGE;
                }

                Graphics2D g2 =
                (Graphics2D) graphics;

                g2.translate(
                    pageFormat.getImageableX(),
                    pageFormat.getImageableY()
                );

                int y = 40;

                // Clinic name
                g2.setFont(
                    new Font(
                        "Arial",
                        Font.BOLD,
                        20
                    )
                );

                g2.drawString(
                    "SUNRISE DENTAL CLINIC",
                    50,
                    y
                );

                y += 30;

                // Bill title
                g2.setFont(
                    new Font(
                        "Arial",
                        Font.BOLD,
                        16
                    )
                );

                g2.drawString(
                    "PATIENT BILL",
                    50,
                    y
                );

                y += 40;

                g2.setFont(
                    new Font(
                        "Arial",
                        Font.PLAIN,
                        13
                    )
                );

                // Appointment ID
                g2.drawString(
                    "Appointment ID : "
                    + txtAppointmentId.getText(),
                    50,
                    y
                );

                y += 25;

                // Patient
                g2.drawString(
                    "Patient Name   : "
                    + txtPatientName.getText(),
                    50,
                    y
                );

                y += 25;

                // Dentist
                g2.drawString(
                    "Dentist Name   : "
                    + txtDentistName.getText(),
                    50,
                    y
                );

                y += 25;

                // Treatment
                g2.drawString(
                    "Treatment      : "
                    + txtTreatment.getText(),
                    50,
                    y
                );

                y += 25;

                // Treatment cost
                g2.drawString(
                    "Treatment Cost : "
                    + txtTreatmentCost.getText(),
                    50,
                    y
                );

                y += 30;

                g2.drawString(
                    "-----------------------------------",
                    50,
                    y
                );

                y += 25;

                // Total
                g2.setFont(
                    new Font(
                        "Arial",
                        Font.BOLD,
                        15
                    )
                );

                g2.drawString(
                    "TOTAL AMOUNT  : "
                    + txtTotal.getText(),
                    50,
                    y
                );

                y += 45;

                g2.setFont(
                    new Font(
                        "Arial",
                        Font.PLAIN,
                        12
                    )
                );

                g2.drawString(
                    "Thank you for choosing Sunrise Dental Clinic.",
                    50,
                    y
                );

                return PAGE_EXISTS;
            }
        });

        boolean printConfirmed =
        printerJob.printDialog();

        if (printConfirmed) {

            try {

                printerJob.print();

                JOptionPane.showMessageDialog(
                    this,
                    "Bill printed successfully.",
                    "Print Bill",
                    JOptionPane.INFORMATION_MESSAGE
                );

            } catch (PrinterException e) {

                JOptionPane.showMessageDialog(
                    this,
                    "Printing failed.\n\n"
                    + e.getMessage(),
                    "Print Error",
                    JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }
        
private void clearBill() {

    txtAppointmentId.setText("");
    txtPatientName.setText("");
    txtDentistName.setText("");
    txtTreatment.setText("");
    txtTreatmentCost.setText("");
    txtTotal.setText("");

    txtAppointmentId.requestFocus();
     
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BillingFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel lblAppointmentId;
    private javax.swing.JLabel lblPDentistName;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTreatment;
    private javax.swing.JLabel lblTreatmentCost;
    private javax.swing.JPanel pn1Bill;
    private javax.swing.JPanel pn1Bill1;
    private javax.swing.JTextField txtAppointmentId;
    private javax.swing.JTextField txtDentistName;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTreatment;
    private javax.swing.JTextField txtTreatmentCost;
    // End of variables declaration//GEN-END:variables
}
