/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sunrisedental.ui;

/**
 *
 * @author my pc
 */
public class DashboardFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardFrame.class.getName());

    /**
     * Creates new form Dashboard
     */
    public DashboardFrame() {
        initComponents();
        
        pn1Dashboard.setBackground(new java.awt.Color(240, 248, 249));

    
    lblTitle.setForeground(new java.awt.Color(20, 76, 84));
    lblTitle.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 22));

   
    lblWelcome.setForeground(new java.awt.Color(82, 110, 116));
    lblWelcome.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));

  
    btnAppointments.setBackground(new java.awt.Color(20, 126, 137));
    btnAppointments.setForeground(java.awt.Color.WHITE);
    btnAppointments.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
    btnAppointments.setFocusPainted(false);
    btnAppointments.setBorderPainted(false);
    btnAppointments.setOpaque(true);

    
    btnSearch.setBackground(new java.awt.Color(214, 239, 241));
    btnSearch.setForeground(new java.awt.Color(20, 100, 110));
    btnSearch.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
    btnSearch.setFocusPainted(false);
    btnSearch.setBorderPainted(false);
    btnSearch.setOpaque(true);
    
     btnBilling.setBackground(new java.awt.Color(214, 239, 241));
    btnBilling.setForeground(new java.awt.Color(20, 100, 110));
    btnBilling.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
    btnBilling.setFocusPainted(false);
    btnBilling.setBorderPainted(false);
    btnBilling.setOpaque(true);
    
    
    btnReports.setBackground(new java.awt.Color(20, 126, 137));
    btnReports.setForeground(java.awt.Color.WHITE);
    btnReports.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
    btnReports.setFocusPainted(false);
    btnReports.setBorderPainted(false);
    btnReports.setOpaque(true);

    
    btnHelp.setBackground(new java.awt.Color(214, 239, 241));
    btnHelp.setForeground(new java.awt.Color(20, 100, 110));
    btnHelp.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
    btnHelp.setFocusPainted(false);
    btnHelp.setBorderPainted(false);
    btnHelp.setOpaque(true);
    
     btnLogout.setBackground(new java.awt.Color(214, 239, 241));
    btnLogout.setForeground(new java.awt.Color(20, 100, 110));
    btnLogout.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
    btnLogout.setFocusPainted(false);
    btnLogout.setBorderPainted(false);
    btnLogout.setOpaque(true);


    setTitle("Sunrise Dental Clinic");
    setResizable(false);
    setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn1Dashboard = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        btnAppointments = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnBilling = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn1Dashboard.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("SUNRISE DENTAL CLINIC");

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblWelcome.setText("Welcome to Clinic Management System");

        btnAppointments.setBackground(new java.awt.Color(0, 153, 255));
        btnAppointments.setText("APPOINTMENTS");
        btnAppointments.addActionListener(this::btnAppointmentsActionPerformed);

        btnSearch.setBackground(new java.awt.Color(51, 153, 255));
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        btnBilling.setBackground(new java.awt.Color(0, 102, 204));
        btnBilling.setText("BILLING");
        btnBilling.addActionListener(this::btnBillingActionPerformed);

        btnReports.setBackground(new java.awt.Color(0, 102, 255));
        btnReports.setText("REPORTS");
        btnReports.addActionListener(this::btnReportsActionPerformed);

        btnLogout.setBackground(new java.awt.Color(0, 102, 255));
        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        btnHelp.setBackground(new java.awt.Color(0, 102, 255));
        btnHelp.setText("HELP");
        btnHelp.addActionListener(this::btnHelpActionPerformed);

        javax.swing.GroupLayout pn1DashboardLayout = new javax.swing.GroupLayout(pn1Dashboard);
        pn1Dashboard.setLayout(pn1DashboardLayout);
        pn1DashboardLayout.setHorizontalGroup(
            pn1DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn1DashboardLayout.createSequentialGroup()
                .addGroup(pn1DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn1DashboardLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn1DashboardLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 83, 83))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn1DashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pn1DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn1DashboardLayout.createSequentialGroup()
                        .addComponent(btnHelp)
                        .addGap(27, 27, 27)
                        .addComponent(btnLogout)
                        .addGap(164, 164, 164))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn1DashboardLayout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
            .addGroup(pn1DashboardLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn1DashboardLayout.setVerticalGroup(
            pn1DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn1DashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(pn1DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(pn1DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(pn1DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn1Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn1Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointmentsActionPerformed
           AppointmentFrame appointmentFrame = new AppointmentFrame();
    appointmentFrame.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnAppointmentsActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
         SearchFrame searchFrame = new SearchFrame();
    searchFrame.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillingActionPerformed
          BillingFrame billFrame = new BillingFrame();
    billFrame.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnBillingActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
         ReportFrame reportFrame = new ReportFrame();
    reportFrame.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
          int choice = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Logout Confirmation",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE
    );

    if (choice == javax.swing.JOptionPane.YES_OPTION) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "You have been logged out successfully.",
                "Logout Successful",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        new Loginframe().setVisible(true);

    }

             
              this.dispose();    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        HelpFrame HelpFrame = new HelpFrame();
            HelpFrame.setVisible(true);
              this.dispose();
    }//GEN-LAST:event_btnHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppointments;
    private javax.swing.JButton btnBilling;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pn1Dashboard;
    // End of variables declaration//GEN-END:variables
}
